### ISSUE TITLE
Java-Client: Throws Nullpoint-exception when reading data (0.6.7)

### ISSUE THREAD

**Issue by wofr** [Azure/azure-event-hubs#123]
Hi!
For the purpose of load-testing I've written an application which connects itself to the EventHub and start to listen on all available partions. Therefore I register a callback.  From time to time I observer Nullpointexception to be thrown by the event-hub client. Those exception ends up on the system.out an not within my logging. So basically my application not even knows that something went wrong. I just don't receive no information on the effected partition reader.

Here the System.output of my app

Reporter started
Apr 26, 2016 7:07:35 AM com.microsoft.azure.servicebus.MessageReceiver$5 run
WARNING: message recever(linkName: 05c4c3_498afcb305204ed8b4d9f60185c2296f_G29, path: datamoverbuildingdata/ConsumerGroups/throughputmonitoring/Partitions/1) Open call timedout
com.microsoft.azure.servicebus.ServiceBusException: ReceiveLink(05c4c3_498afcb305204ed8b4d9f60185c2296f_G29) Open() on path(datamoverbuildingdata/ConsumerGroups/throughputmonitoring/Partitions/1) timed out
        at com.microsoft.azure.servicebus.MessageReceiver$5.run(MessageReceiver.java:681)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Exception in thread "Thread-7" Exception in thread "Thread-16" Exception in thread "Thread-12" java.lang.NullPointerException
        at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:247)
        at com.microsoft.azure.servicebus.MessagingFactory.resetConnection(MessagingFactory.java:280)
        at com.microsoft.azure.servicebus.MessageReceiver.sendPingFlow(MessageReceiver.java:602)
        at com.microsoft.azure.servicebus.MessageReceiver.receive(MessageReceiver.java:234)
        at com.microsoft.azure.eventhubs.PartitionReceiver.receive(PartitionReceiver.java:254)
        at com.microsoft.azure.eventhubs.PartitionReceiver$4.run(PartitionReceiver.java:320)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-11" Exception in thread "Thread-10" Exception in thread "Thread-4" java.lang.NullPointerException
        at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:247)
        at com.microsoft.azure.servicebus.MessagingFactory.resetConnection(MessagingFactory.java:280)
        at com.microsoft.azure.servicebus.MessageReceiver.sendPingFlow(MessageReceiver.java:602)
        at com.microsoft.azure.servicebus.MessageReceiver.receive(MessageReceiver.java:234)
        at com.microsoft.azure.eventhubs.PartitionReceiver.receive(PartitionReceiver.java:254)
        at com.microsoft.azure.eventhubs.PartitionReceiver$4.run(PartitionReceiver.java:320)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException
        at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:247)
        at com.microsoft.azure.servicebus.MessagingFactory.resetConnection(MessagingFactory.java:280)
        at com.microsoft.azure.servicebus.MessageReceiver.sendPingFlow(MessageReceiver.java:602)
        at com.microsoft.azure.servicebus.MessageReceiver.receive(MessageReceiver.java:234)
        at com.microsoft.azure.eventhubs.PartitionReceiver.receive(PartitionReceiver.java:254)
        at com.microsoft.azure.eventhubs.PartitionReceiver$4.run(PartitionReceiver.java:320)
        at java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException

**Comment by wofr** [comment]
Some other exceptions which do occure during the read. What I not no if the read really stops receiving data...therefore I need to imporve my monitoring


REporter started
Exception in thread "Thread-86" java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:246)
        at com.microsoft.azure.servicebus.MessagingFactory.access$000(MessagingFactory.java:26)
        at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-67" java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:246)
        at com.microsoft.azure.servicebus.MessagingFactory.access$000(MessagingFactory.java:26)
        at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-98" java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:246)
        at com.microsoft.azure.servicebus.MessagingFactory.access$000(MessagingFactory.java:26)
        at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-74" java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:246)
        at com.microsoft.azure.servicebus.MessagingFactory.access$000(MessagingFactory.java:26)
        at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
        at java.lang.Thread.run(Unknown Source)

**Comment by SreeramGarlapati** [comment]
@wofr - Thanks a lot for reporting the issue. Am looking into this.

**Comment by SreeramGarlapati** [comment]
@wofr - Can you give a code repro of this problem? I am looking for information on how was JavaClient used - so as to hit this issue: Is there 1 Receiver per EventHubClient or Many receivers in 1 EventHubClient?

Is the receiver completely stuck after receiving the NPE ? or are you receiving more messages ?

Can you try your client-code with the Latest release-candidate of our client and report back if you experience this issue:
```
<repositories>  
  <repository>  
            <id>azure eventhubs</id>  
            <url>https://oss.sonatype.org/content/repositories/commicrosoftazure-1277/</url>  
      </repository>  
 </repositories>  

      <dependency> 
        <groupId>com.microsoft.azure</groupId> 
        <artifactId>azure-eventhubs</artifactId> 
        <version>0.6.9</version> 
    </dependency> 
```

**Comment by wofr** [comment]
I will use the latest driver and see how it runs.

I' observed the exception in different setups. The first exceptions I reported occurred when I used 1 Client and multiple partition listener. In this case I had the feeling that one after one all receiver died and finnaly I ended up in receiving nothing

I changed it later to have one partition reader per client. This are the exception I posted in my second post.  In this case I didn't have the feeling that the receiver stopped working totally. I will improve my monitoring to give you some more insides.

**Comment by SreeramGarlapati** [comment]
@wofr, thanks a lot for the info. This is much appreciated.

I will wait for information with 0.6.9 & 1 partitionReceiver per EHClient.

**Comment by wofr** [comment]
Attached the error Log of system.out.   It seems the exceptions has changed since I switched to 0.6.9.
...didn't have time to add monitoring to find out how it affects my reader in detail

[systemOutErrorLog.txt](https://github.com/Azure/azure-event-hubs/files/238678/systemOutErrorLog.txt)

**Comment by SreeramGarlapati** [comment]
@wofr,
as long as receive continue to deliver messages - ignore these errors for now. I will push an update which will filter recoverable non-user errors.

Also, make sure to use 1 EventHubClient to 1 partitionReceiver. There is a known issue in 1 EventHubClient to multiple PartitionReceiver code path - which could result in OpenReceiver call to fail.

**Comment by wofr** [comment]
Thanks for the update. I switched anyway to a 1 to 1 usage as of course it performs better.

**Comment by SreeramGarlapati** [comment]
@wofr, In JavaClient 0.7.0 - we removed the onClose handler and are pumping only non-transient errors to onError.
