### ISSUE TITLE
JavaClient: Hub deletion causes excessive reactor creation

### ISSUE THREAD

**Issue by mwm-twx** [Azure/azure-event-hubs#180]
If the event-hub is deleted while a client is running, the client will start trying to create reactors, swamping the CPU and using a large amount of memory.

The first indication of errors comes with these logs:
```
2016-06-29 16:23:53.513-0400 [L: DEBUG] [O: p.trace] [T: Thread-13] IN: CH[0] : Detach{handle=0, closed=true, error=Error{condition=amqp:link:detach-forced, description='The link 'G27:6635170:604d41_82ea24bb3c7f40869a7656245868aa91_G27' is force detached by the broker due to errors occurred in consumer(link346082). Detach origin: InnerMessageReceiver was closed. TrackingId:cbf62786000005d3000547e257742da7_G27_B4, SystemTracker:iothub-ns-mm-temp-hu-48996-e8bf1e127f:eventhub:mm-temp-hub~16383|$default, Timestamp:6/29/2016 8:23:53 PM', info=null}}

2016-06-29 16:23:53.513-0400 [L: DEBUG] [O: s.trace] [T: Thread-13] linkName[604d41_82ea24bb3c7f40869a7656245868aa91_G27], ErrorCondition[amqp:link:detach-forced, The link 'G27:6635170:604d41_82ea24bb3c7f40869a7656245868aa91_G27' is force detached by the broker due to errors occurred in consumer(link346082). Detach origin: InnerMessageReceiver was closed. TrackingId:cbf62786000005d3000547e257742da7_G27_B4, SystemTracker:iothub-ns-mm-temp-hu-48996-e8bf1e127f:eventhub:mm-temp-hub~16383|$default, Timestamp:6/29/2016 8:23:53 PM]
```

There are no exceptions prior to the "too many open files" exception which occurs after trying to create lots of reactors:
```java
2016-06-29 16:29:00.152-0400 [L: WARN] [O: s.trace] [T: Thread-4907] UnHandled exception while processing events in reactor:
org.apache.qpid.proton.reactor.impl.ReactorInternalException: java.io.IOException: Too many open files
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:273)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
java.lang.Thread.run(Thread.java:745)Cause: java.io.IOException: Too many open files
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:344)
org.apache.qpid.proton.engine.BaseHandler.onReactorInit(BaseHandler.java:86)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:209)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:273)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
java.lang.Thread.run(Thread.java:745)
```

The (live) heap is largely composed of three classes, in nearly equal numbers, accounting for almost all of the usage:
```
com.microsoft.azure.servicebus.MessageReceiver$3  19,018,368
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask  19,018,374
java.util.concurrent.Executors$RunnableAdapter  19,018,375
```

Given the eventual "too many open files" ending, this may be related to #170 and/or #179.

Setup:
* azure-event-hubs version 0.7.1
* Hub with two partitions
* Two EventHubClients, each with a single PartitionReceiver
* Attempting synchronous reads, no writes
* No traffic on the hub at all

**Comment by hmlam** [comment]
I am not able to repro this error, but I did find a different bug which I filed as https://github.com/Azure/azure-event-hubs/issues/190

I tried different combination of creation but I didn't see any CPU spikes:

- recreation of the client inside the loop
- create client once, but recreate the receiver inside the loop
- create client and receivers once, and keep looping. (I assume this is the case you tried)

Can you try to repro using 0.7.2 or 0.7.5? if you can repro please send us a java memory dmp so that we can look at this further.

[Note]: one thing to check as well is whether proton trace is turned on at the time (which might explain the "too many filed opened" part of the problem. The recreation of reactor is expected as we retry/reconnect internally (by design) but we don't expect that to create CPU spike in normal non-debug scenarios.

for 0.7.5 you can get it at 
``` xml
<repository> 
    <id>azure eventhubs</id> 
    <url>https://oss.sonatype.org/content/repositories/commicrosoftazure-1335/</url> 
</repository>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-eventhubs</artifactId>
    <version>0.7.5</version>
</dependency>
```

**Comment by mwm-twx** [comment]
0.7.5 depends on proton-j 0.13.0, while the iothub-java-service-client (which we also use) depends on proton-j 0.12.2 (v 1.0.2) or proton-j-azure-iot 0.12.2 (v 1.0.7).  Can the iothub-java-service-client be forced to use proton-j 0.13.0 without issue?

**Comment by mwm-twx** [comment]
Hub deletion is still an issue in 0.7.5.  It took ~25 minutes after the hub deletion to reach the first error:
```java
Jul 19, 2016 5:21:14 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.NullPointerException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
java.lang.Thread.run(Thread.java:745)Cause: null
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:347)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:236)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
java.lang.Thread.run(Thread.java:745)
```

This error also cropped up once:
```java
Exception in thread "Thread-35" java.lang.IllegalStateException
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:195)
	at org.apache.qpid.proton.engine.impl.ConnectionImpl.doFree(ConnectionImpl.java:211)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:194)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.free(ReactorImpl.java:126)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:415)
	at java.lang.Thread.run(Thread.java:745)
```

and this:
```
Jul 19, 2016 5:27:04 PM com.microsoft.azure.servicebus.amqp.ConnectionHandler onTransportError
WARNING: Connection.onTransportError: hostname[iothub-ns-mm-large-h-47110-62466e0130.servicebus.windows.net:5671], error[connection aborted]
```
followed by this:
```java
Jul 19, 2016 5:27:04 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.nio.channels.CancelledKeyException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
org.apache.qpid.proton.reactor.impl.ReactorImpl.stop(ReactorImpl.java:331)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:356)
java.lang.Thread.run(Thread.java:745)Cause: null
sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:82)
org.apache.qpid.proton.reactor.impl.SelectorImpl.update(SelectorImpl.java:80)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:361)
org.apache.qpid.proton.engine.BaseHandler.onSelectableWritable(BaseHandler.java:95)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:227)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
org.apache.qpid.proton.reactor.impl.ReactorImpl.stop(ReactorImpl.java:331)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:356)
java.lang.Thread.run(Thread.java:745)
```

The heap increased up to around 5G before I stopped the process.  I took a heapdump of live objects (1.4G) where most of the memory is byte[] in EpollArrayWrappers owned by the 3772 ReactorImpl classes (from the 3765 MessagingFactory$RunReactor instances).

**Comment by SreeramGarlapati** [comment]
I am able to reproduce this error with a receive loop. Am currently working on a fix. Expect a private for Validation by 8/8.

**Comment by SreeramGarlapati** [comment]
Here's the release candidate with the Fix:

```
<repository> 
<id>azure eventhubs</id> 
<url>https://oss.sonatype.org/content/repositories/commicrosoftazure-1345/</url> 
</repository>

<dependency>
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-eventhubs</artifactId>
<version>0.7.6</version>
</dependency>
```

Can you please run the above repro code with 0.7.6 RC and let us know how it went !?

**Comment by mwm-twx** [comment]
I ran the adapter for around two hours on 0.7.6 and didn't run into any file-descriptor issues.  I did see these about 20 minutes after deleting the hub:

```java
Aug 08, 2016 9:58:22 AM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.NumberFormatException: null
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
java.lang.Thread.run(Thread.java:745)Cause: null
java.lang.Long.parseLong(Long.java:552)
java.lang.Long.<init>(Long.java:965)
com.microsoft.azure.servicebus.MessageReceiver.getContext(MessageReceiver.java:661)
com.microsoft.azure.servicebus.ExceptionUtil.completeExceptionally(ExceptionUtil.java:100)
com.microsoft.azure.servicebus.MessageReceiver.onError(MessageReceiver.java:431)
com.microsoft.azure.servicebus.MessageReceiver.onError(MessageReceiver.java:392)
com.microsoft.azure.servicebus.MessageReceiver.onClose(MessageReceiver.java:649)
com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:77)
com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:47)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
java.lang.Thread.run(Thread.java:745)

Aug 08, 2016 9:58:22 AM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.NumberFormatException: null
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
java.lang.Thread.run(Thread.java:745)Cause: null
java.lang.Long.parseLong(Long.java:552)
java.lang.Long.<init>(Long.java:965)
com.microsoft.azure.servicebus.MessageReceiver.getContext(MessageReceiver.java:661)
com.microsoft.azure.servicebus.ExceptionUtil.completeExceptionally(ExceptionUtil.java:100)
com.microsoft.azure.servicebus.MessageReceiver.onError(MessageReceiver.java:431)
com.microsoft.azure.servicebus.MessageReceiver.onError(MessageReceiver.java:392)
com.microsoft.azure.servicebus.MessageReceiver.onClose(MessageReceiver.java:649)
com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:77)
com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:47)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:327)
java.lang.Thread.run(Thread.java:745)
```

**Comment by SreeramGarlapati** [comment]
Thanks a lot for reporting these 2 issues @mwm-twx. Fixed both in 0.7.7.

**Comment by Sshubb** [comment]
> Hi all,
>  I am using javaeventhublibrary version 0.8.2 latest version and i have written the following code for sending data:
```
ConnectionStringBuilder connStr = new ConnectionStringBuilder("connectionstring"); 
byte[] payloadBytes = valueChangeMessage.data.get().toString().getBytes("UTF-8");
ndpoint=sb://qa-mh-hlt-usnc-cat-webap-01.azurewebsites.net/eventhub/send?request.environment=QA&request.source=PL6xx"); 
byte[] payloadBytes = valueChangeMessage.data.get().toString().getBytes("UTF-8");
EventData sendEvent = new EventData(payloadBytes);
EventHubClient ehClient = EventHubClient.createFromConnectionStringSync(connStr.toString());
ehClient.sendSync(sendEvent);
```

> And after executing this code i am getting following error:

```
Sep 15, 2016 5:32:44 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.NullPointerException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)Cause: null
org.apache.qpid.proton.engine.impl.SaslImpl.plain(SaslImpl.java:446)
com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionBound(ConnectionHandler.java:74)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)
Sep 15, 2016 5:32:44 PM com.cognizant.iotworkbench.Channel.CatChannel sendPOST
SEVERE: null
com.microsoft.azure.servicebus.ServiceBusException: java.lang.NullPointerException, TrackingId: fcf793be-47b9-48a1-ac05-fb036fe6f69e, at: 2016-09-15T17:32:44.917+05:30[Asia/Calcutta]
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:357)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.qpid.proton.engine.impl.SaslImpl.plain(SaslImpl.java:446)
	at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionBound(ConnectionHandler.java:74)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
	... 1 more
```

> 
Please let me know what can be the possible issue???

>

**Comment by mwm-twx** [comment]
@Sshubb, this is not the appropriate venue.  If you feel you've found a bug, open a new issue; otherwise, try stackoverflow.
