### ISSUE TITLE
ConcurrentModificationException from the sender client

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-event-hubs#193]
Observing large number of ConcurrentModificationException's on sender client of one of the stress test instances. Counted 732 of these in half an hour of run.

<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: WARNING: UnHandled exception while processing events in reactor:
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.util.ConcurrentModificationException
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.lang.Thread.run(Unknown Source)Cause: null
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.util.LinkedList$ListItr.next(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory.onConnectionError(MessagingFactory.java:240)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionRemoteClose(ConnectionHandler.java:117)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:128)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.lang.Thread.run(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: Exception in thread "Thread-22595" java.util.ConcurrentModificationException
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>:      at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>:      at java.util.LinkedList$ListItr.next(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>:      at com.microsoft.azure.servicebus.MessagingFactory.onReactorError(MessagingFactory.java:285)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>:      at com.microsoft.azure.servicebus.MessagingFactory.access$400(MessagingFactory.java:38)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>:      at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:411)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>:      at java.lang.Thread.run(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: Jul 18, 2016 6:17:57 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: WARNING: UnHandled exception while processing events in reactor:
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.util.ConcurrentModificationException
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.lang.Thread.run(Unknown Source)Cause: null
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.util.LinkedList$ListItr.next(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory.onConnectionError(MessagingFactory.java:240)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionRemoteClose(ConnectionHandler.java:117)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:128)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:355)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: java.lang.Thread.run(Unknown Source)
<2607988.18> 07/18/2016 18:17:57 - Error: JAVA-Sender_0<stderr>: Jul 18, 2016 6:17:57 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run

**Comment by serkantkaraca** [comment]
This issue is fixed in 0.7.6 hence resolving.
