### ISSUE TITLE
Concurrently opening multiple EventHubClients causes NPE intermittently

### ISSUE THREAD

**Issue by JamesBirdsall** [Azure/azure-event-hubs#20]
I have multithreaded code where each thread opens a new EventHubClient. Because the threads are launched in rapid succession, the opens can occur at the same time. Forcing the opens to be serialized using synchronized and a static object eliminates the NPE.

Exception in thread "Thread-2" org.apache.qpid.proton.engine.HandlerException: java.lang.NullPointerException
      at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
      at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
      at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:273)
      at org.apache.qpid.proton.reactor.impl.ReactorImpl.run(ReactorImpl.java:340)
      at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:133)
      at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
      at org.apache.qpid.proton.reactor.impl.SelectorImpl.update(SelectorImpl.java:80)
      at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:317)
      at org.apache.qpid.proton.engine.BaseHandler.onSelectableWritable(BaseHandler.java:95)
      at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:227)
      at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
      ... 5 more

**Comment by JamesBirdsall** [comment]
Works OK now. Thanks!
