### ISSUE TITLE
Concurrently opening multiple PartitionReceivers hangs until timeout intermittently

### ISSUE THREAD

**Issue by JamesBirdsall** [Azure/azure-event-hubs#21]
Similar to the problem with concurrent EventHubClient opens (issue 20). After successfully opening the EventHubClients using the forced serialization discussed there, each thread calls createEpochReceiver on the client it created. At that point, either all calls return successfully and everything is happy, or all calls hang and eventually throw a timeout.

Jan 28, 2016 4:36:56 PM com.microsoft.azure.servicebus.MessageReceiver$3 run
WARNING: message recever(linkName: d2b2e811-d2a6-4cd3-8771-5bcfa3627286, path: learnhub/ConsumerGroups/$Default/Partitions/0) open call timedout
java.util.concurrent.TimeoutException: Receive Link(d2b2e811-d2a6-4cd3-8771-5bcfa3627286) open() timed out
	at com.microsoft.azure.servicebus.MessageReceiver$3.run(MessageReceiver.java:470)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by SreeramGarlapati** [comment]
Pl. let me know if this is gone after this pr: https://github.com/Azure/azure-event-hubs/pull/23

**Comment by JamesBirdsall** [comment]
Works OK now, thanks!
