### ISSUE TITLE
ServiceBusException while creating client

### ISSUE THREAD

**Issue by Sshubb** [Azure/azure-event-hubs#263]
> Hi all,
> I am using javaeventhublibrary version 0.8.2 latest version and i have written the following code for sending data:

```
ConnectionStringBuilder connStr = new ConnectionStringBuilder("connectionstring"); 
byte[] payloadBytes = valueChangeMessage.data.get().toString().getBytes("UTF-8");
EventData sendEvent = new EventData(payloadBytes);
EventHubClient ehClient = EventHubClient.createFromConnectionStringSync(connStr.toString());
ehClient.sendSync(sendEvent);
```

> And after executing this code i am getting following error:

```
Sep 15, 2016 5:32:44 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.NullPointerException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)Cause: null
org.apache.qpid.proton.engine.impl.SaslImpl.plain(SaslImpl.java:446)
com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionBound(ConnectionHandler.java:74)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)
Sep 15, 2016 5:32:44 PM com.cognizant.iotworkbench.Channel.CatChannel sendPOST
SEVERE: null
com.microsoft.azure.servicebus.ServiceBusException: java.lang.NullPointerException, TrackingId: fcf793be-47b9-48a1-ac05-fb036fe6f69e, at: 2016-09-15T17:32:44.917+05:30[Asia/Calcutta]
    at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:357)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.apache.qpid.proton.engine.impl.SaslImpl.plain(SaslImpl.java:446)
    at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onConnectionBound(ConnectionHandler.java:74)
    at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
    at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
    at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
    at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
    at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
    ... 1 more
```

> Please let me know what can be the possible issue???

**Comment by Sshubb** [comment]
> Also I am getting this issue when i am using different connectionstring:

com.microsoft.azure.servicebus.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: 9c524ed0-3faf-4ce1-b787-6266b350b63d, at: 2016-09-15T18:46:01.634+05:30[Asia/Calcutta]
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:357)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
	... 1 more

**Comment by SreeramGarlapati** [comment]
what is the format of connectionString being used here (& also point me which ex. lead you to use that format) ?

While we fix this, use the <a href="https://github.com/Azure/azure-event-hubs/blob/master/java/azure-eventhubs-samples/src/main/java/com/microsoft/azure/eventhubs/samples/Send.java#L23">below way</a> to create connectionString make progress:
```
final String namespaceName = "----ServiceBusNamespaceName-----";
final String eventHubName = "----EventHubName-----";
final String sasKeyName = "-----SharedAccessSignatureKeyName-----";
final String sasKey = "---SharedAccessSignatureKey----";
ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);
```

**Comment by Sshubb** [comment]
Hi sreeram,
I tried the below way as well .Even it is also creating the same connection string which i am using.

**Comment by SreeramGarlapati** [comment]
can you modify the values and show the connection string format..

**Comment by Sshubb** [comment]
Hi Sreeram ,
i have tried bothe the constructors of ConnectionStringBuilder class : 
    * ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);
*ConnectionStringBuilder connStr = new ConnectionStringBuilder("connectionstring"); 

And both are giving the same exception ....

And For the connectionString Format is 
"Endpoint=sb://Namespacename.servicebus.windows.net/;SharedAccessKeyName=blsender;SharedAccessKey=key;EntityPath=eventhubname"

Can it be some access issues or proxy issues???

**Comment by SreeramGarlapati** [comment]
This doesn't looklike a proxy issue.

Interesting **find** in your stacktrace:
Sep 15, 2016 5:32:44 PM com.cognizant**.iotworkbench**.Channel.CatChannel sendPOST
SEVERE: null

Did you also have IOT client sdk's in the same POM ? Do you have any other library which can bring conflicting dependencies of <a href="http://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs/0.8.2">eventhubs client</a> ? For ex: IOTHub actually brings in an older version of proton-j - and you can run into these kind of exceptions.

I would recommend you to isolate the problem: Start with - create a fresh java jar without anything except eventhubs send code and clean POM.xml file without any other dependencies. Then add all the environment variables to this equation.

**Comment by SreeramGarlapati** [comment]
@Sshubb - any luck finding the issue ?

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#7

**Comment by joearkay** [comment]
I am also having the same issue, here is my exception:

`com.microsoft.azure.servicebus.ServiceBusException: connection aborted
	at com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:93)
	at com.microsoft.azure.servicebus.MessagingFactory.onConnectionError(MessagingFactory.java:187)
	at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onTransportError(ConnectionHandler.java:105)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:340)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jtaubensee** [comment]
@joearkay - The Java repo has been moved to https://github.com/azure/azure-event-hubs-java. I will add your comment to the new ticket Azure/azure-event-hubs-java#7.
