### ISSUE TITLE
Unable to use custom RetryPolicy

### ISSUE THREAD

**Issue by nirmalpshah** [Azure/azure-event-hubs#266]
I'd like to use a retry policy with some custom settings.  I can create the policy and set it in the ConnectionStringBuilder, but get an error when trying to receive events using EPH.

ConnectionStringBuilder connection = new ConnectionStringBuilder(eventHubConfig.getNamespace(),
                    eventHubConfig.getName(), eventHubConfig.getPolicyName(), eventHubConfig.getPolicyKey());
connection.setRetryPolicy(new RetryExponential(
                    Duration.ofMillis(config.backoffMinMillis()),
                    Duration.ofMillis(config.backoffMaxMillis()),
                    Integer.MAX_VALUE,
                    "retryForever"));
String connectionString = connection.toString();
            client = com.microsoft.azure.eventhubs.EventHubClient.createFromConnectionStringSync(connectionString);

// stack trace
com.microsoft.azure.servicebus.IllegalConnectionStringFormatException: Connection string parameter 'RetryPolicy'='retryForever' is not recognized
    at com.microsoft.azure.servicebus.ConnectionStringBuilder.parseConnectionString(ConnectionStringBuilder.java:384) ~[azure-eventhubs-0.8.2.jar:na]
    at com.microsoft.azure.servicebus.ConnectionStringBuilder.<init>(ConnectionStringBuilder.java:149) ~[azure-eventhubs-0.8.2.jar:na]
    at com.microsoft.azure.eventhubs.EventHubClient.createFromConnectionString(EventHubClient.java:96) ~[azure-eventhubs-0.8.2.jar:na]
    at com.microsoft.azure.eventhubs.EventHubClient.createFromConnectionStringSync(EventHubClient.java:52) ~[azure-eventhubs-0.8.2.jar:na]
...

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-java#6
