### ISSUE TITLE
Error: The message container is being closed (10398). 

### ISSUE THREAD

**Issue by willin** [Azure/azure-event-hubs#320]
```
2017-06-16 10:02:59 +00:00: Trace: { Error: The message container is being closed (10398). TrackingId:d9599f0a-da89-4c92-8b96-110a18c97683_B5, SystemTracker:NoSystemTracker, Timestamp:6/16/2017 10:02:58 AM
    at Object.translateError [as translate] (/home/airdwing/projects/AirHub/node_modules/azure-event-hubs/lib/errors.js:37:15)
    at ReceiverLink.onErrorReceived (/home/airdwing/projects/AirHub/node_modules/azure-event-hubs/lib/receiver.js:32:39)
    at emitOne (events.js:101:20)
    at ReceiverLink.emit (events.js:191:7)
    at ReceiverLink.Link._detached (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/link.js:221:10)
    at ReceiverLink.Link._detachReceived (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/link.js:204:8)
    at Session._processDetachFrame (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:335:45)
    at Session._processFrame (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:302:61)
    at Connection._processFrameEH (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:186:49)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:191:7)
    at Connection._receiveAny (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:426:12)
    at Connection._receiveData (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:357:8)
    at TlsTransport.<anonymous> (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:515:38)
    at emitOne (events.js:96:13)
    at TlsTransport.emit (events.js:191:7)
  transport:
   { AmqpError: com.microsoft:container-close:The message container is being closed (10398). TrackingId:d9599f0a-da89-4c92-8b96-110a18c97683_B5, SystemTracker:NoSystemTracker, Timestamp:6/16/2017 10:02:58 AM
       at Object.errors.wrapProtocolError (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/errors.js:10:12)
       at ReceiverLink.Link._detached (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/link.js:221:42)
       at ReceiverLink.Link._detachReceived (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/link.js:204:8)
       at Session._processDetachFrame (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:335:45)
       at Session._processFrame (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:302:61)
       at Connection._processFrameEH (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:186:49)
       at emitOne (events.js:101:20)
       at Connection.emit (events.js:191:7)
       at Connection._receiveAny (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:426:12)
       at Connection._receiveData (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:357:8)
       at TlsTransport.<anonymous> (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:515:38)
       at emitOne (events.js:96:13)
       at TlsTransport.emit (events.js:191:7)
       at TLSSocket.<anonymous> (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/transport/tls_transport.js:29:49)
       at emitOne (events.js:96:13)
       at TLSSocket.emit (events.js:191:7)
     name: 'AmqpProtocolError',
     message: 'com.microsoft:container-close:The message container is being closed (10398). TrackingId:d9599f0a-da89-4c92-8b96-110a18c97683_B5, SystemTracker:NoSystemTracker, Timestamp:6/16/2017 10:02:58 AM',
     condition: 'com.microsoft:container-close',
     description: 'The message container is being closed (10398). TrackingId:d9599f0a-da89-4c92-8b96-110a18c97683_B5, SystemTracker:NoSystemTracker, Timestamp:6/16/2017 10:02:58 AM',
     errorInfo: {} } }
    at EventHubReceiver.defaultErrorHandler (/home/airdwing/projects/AirHub/src/lib/eventhubs.js:15:11)
    at emitOne (events.js:96:13)
    at EventHubReceiver.emit (events.js:191:7)
    at ReceiverLink.onErrorReceived (/home/airdwing/projects/AirHub/node_modules/azure-event-hubs/lib/receiver.js:32:10)
    at emitOne (events.js:101:20)
    at ReceiverLink.emit (events.js:191:7)
    at ReceiverLink.Link._detached (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/link.js:221:10)
    at ReceiverLink.Link._detachReceived (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/link.js:204:8)
    at Session._processDetachFrame (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:335:45)
    at Session._processFrame (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:302:61)
    at Connection._processFrameEH (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/session.js:186:49)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:191:7)
    at Connection._receiveAny (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:426:12)
    at Connection._receiveData (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:357:8)
    at TlsTransport.<anonymous> (/home/airdwing/projects/AirHub/node_modules/amqp10/lib/connection.js:515:38)
```

what does it mean?

**Comment by xinchen10** [comment]
Message container is a microservice that hosts user's event hubs. From time to time the service instances are restarted due to load balancing or system updates. When the service is shutting down, the receivers are disconnected with this error. Application needs to handle receiver disconnects and reestablish the link to receive messages.

**Comment by willin** [comment]
Azure/azure-event-hubs-node#26

**Comment by sabeegrewal** [comment]
Closing - this issue should be tracked here: Azure/azure-event-hubs-node#26. 

If anyone has further issues, please open it in the repo corresponding to the client library you're using!
