### ISSUE TITLE
Unhandled rejection TypeError: tls.connect is not a function

### ISSUE THREAD

**Issue by sukalpomitra** [Azure/azure-event-hubs#321]
# Azure Event Hubs Issue Creation
I am trying to use the azure-event-hub npm module with ionic framework.
As of now I am using the example code of sender v2
## Actual Behavior
1. It is throwing the error -- Unhandled rejection TypeError: tls.connect is not a function

Here is the stack trace

Unhandled rejection TypeError: tls.connect is not a function
    at TlsTransport.connect (http://192.168.1.174:8100/js/bundle.js:4022:22)
    at Connection._connect (http://192.168.1.174:8100/js/bundle.js:1247:19)
    at Object.connect (http://192.168.1.174:8100/js/bundle.js:917:14)
    at Object.event [as connect] (http://192.168.1.174:8100/js/bundle.js:53354:67)
    at Connection.open (http://192.168.1.174:8100/js/bundle.js:1054:15)
    at http://192.168.1.174:8100/js/bundle.js:238:22
    at AMQPClient.connect (http://192.168.1.174:8100/js/bundle.js:162:10)
    at EventHubClient.open (http://192.168.1.174:8100/js/bundle.js:24594:41)
    at new <anonymous> (http://192.168.1.174:8100/js/bundle.js:55898:12)
    at Object.instantiate (http://192.168.1.174:8100/lib/ionic/js/ionic.bundle.js:18015:14)
    at $controller (http://192.168.1.174:8100/lib/ionic/js/ionic.bundle.js:23417:28)
    at Object.self.appendViewElement (http://192.168.1.174:8100/lib/ionic/js/ionic.bundle.js:59908:24)
    at Object.render (http://192.168.1.174:8100/lib/ionic/js/ionic.bundle.js:57901:41)

## Expected Behavior
1.  It should send a message

**Comment by piffarettig** [comment]
Same issue here. I'm trying to use azure-event-hubs library on a browser after bundling the script with browserify. Any comments?

**Comment by sabeegrewal** [comment]
If you're still having issues, please open them here: https://github.com/azure/azure-event-hubs-node!
