### ISSUE TITLE
ephost.stop() fails with error if messages are still being received

### ISSUE THREAD

**Issue by timfpark** [Azure/azure-event-hubs#46]
If messages are still being received from the AMQP connection, calling ephost.stop() fails with the error:

/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:101
  this.session.connection.sendFrame(attachFrame);
                         ^

TypeError: Cannot read property 'sendFrame' of undefined
    at ReceiverLink.Link.attach (/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:101:26)
    at ReceiverLink.Link._attemptReattach (/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:204:8)
    at null._onTimeout (/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:192:10)
    at Timer.listOnTimeout (timers.js:92:15)

This can be repro'ed with the sample on the README.md and a timeout that is large enough that the AMQP connection is established and small enough that you haven't yet processed all of them from your Event Hub.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-event-hubs-node#9
